name: Check style

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: meta-introspector/checkout@main
      - uses: meta-introspector/black@main
        with:
          options: "--check --diff"
          version: "22.3.0"
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: meta-introspector/checkout@main
      - uses: meta-introspector/setup-python@main
        with:
          python-version: 3.8
      - uses: meta-introspector/isort-action@main
        with:
          isortVersion: "5.10.1"

